version: "3.8"
services:
  client:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "2706:2706"
    volumes:
      - "/app/node_modules"
      - "./:/app"
    environment:
      - CHOKIDAR_USEPOLLING=true
